name: Deploy to Azure

on:
  push:
    branches:
      - main  # or any branch you want to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or whichever version you're using

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # if you have a build script

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <Your_Azure_App_Name>  # Replace with your Azure Web App name
          slot-name: 'production'  # or your desired slot
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # If using publish profiles
          package: .  # Path to your app package (can be a specific folder)

