name: Node.js CI

on:
  push:
    branches: [ "testingdeploy" ]
  pull_request:
    branches: [ "testingdeploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npx jest --coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Your Coveralls repo token
